//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.12 at 11:27:35 PM CEST 
//


package xmlproject.be.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Author_QNAME = new QName("author");
    private final static QName _Abstract_QNAME = new QName("abstract");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Review.Questionnaire.QuestionElement }
     * 
     */
    public Review.Questionnaire.QuestionElement createReviewQuestionnaireQuestionElement() {
        return new Review.Questionnaire.QuestionElement();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Review.Questionnaire }
     * 
     */
    public Review.Questionnaire createReviewQuestionnaire() {
        return new Review.Questionnaire();
    }

    /**
     * Create an instance of {@link Process.Reviews }
     * 
     */
    public Process.Reviews createProcessReviews() {
        return new Process.Reviews();
    }

    /**
     * Create an instance of {@link Review.Comments }
     * 
     */
    public Review.Comments createReviewComments() {
        return new Review.Comments();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Process.Reviews.ReviewElement }
     * 
     */
    public Process.Reviews.ReviewElement createProcessReviewsReviewElement() {
        return new Process.Reviews.ReviewElement();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link CoverLetter }
     * 
     */
    public CoverLetter createCoverLetter() {
        return new CoverLetter();
    }

    /**
     * Create an instance of {@link Review.ConfidentalComments }
     * 
     */
    public Review.ConfidentalComments createReviewConfidentalComments() {
        return new Review.ConfidentalComments();
    }
    
    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Article.References }
     * 
     */
    public Article.References createArticleReferences() {
        return new Article.References();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Article.References.Reference.Publisher }
     * 
     */
    public Article.References.Reference.Publisher createArticleReferencesReferencePublisher() {
        return new Article.References.Reference.Publisher();
    }

    /**
     * Create an instance of {@link Article.References.Reference }
     * 
     */
    public Article.References.Reference createArticleReferencesReference() {
        return new Article.References.Reference();
    }

    /**
     * Create an instance of {@link Article.Sections }
     * 
     */
    public Article.Sections createArticleSections() {
        return new Article.Sections();
    }

    /**
     * Create an instance of {@link Author.University }
     * 
     */
    public Author.University createAuthorUniversity() {
        return new Author.University();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Article.Authors }
     * 
     */
    public Article.Authors createArticleAuthors() {
        return new Article.Authors();
    }

    /**
     * Create an instance of {@link Abstract.Keywords }
     * 
     */
    public Abstract.Keywords createAbstractKeywords() {
        return new Abstract.Keywords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Author }{@code >}}
     * 
     */
    @XmlElementDecl(name = "author")
    public JAXBElement<Author> createAuthor(Author value) {
        return new JAXBElement<Author>(_Author_QNAME, Author.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Abstract }{@code >}}
     * 
     */
    @XmlElementDecl(name = "abstract")
    public JAXBElement<Abstract> createAbstract(Abstract value) {
        return new JAXBElement<Abstract>(_Abstract_QNAME, Abstract.class, null, value);
    }

}
